# Generated by Django 4.0 on 2022-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('concurso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_sorteio', models.DateField()),
                ('B1', models.SmallIntegerField()),
                ('B2', models.SmallIntegerField()),
                ('B3', models.SmallIntegerField()),
                ('B4', models.SmallIntegerField()),
                ('B5', models.SmallIntegerField()),
                ('B6', models.SmallIntegerField()),
                ('B7', models.SmallIntegerField()),
                ('B8', models.SmallIntegerField()),
                ('B9', models.SmallIntegerField()),
                ('B10', models.SmallIntegerField()),
                ('B11', models.SmallIntegerField()),
                ('B12', models.SmallIntegerField()),
                ('B13', models.SmallIntegerField()),
                ('B14', models.SmallIntegerField()),
                ('B15', models.SmallIntegerField()),
                ('qtd_ganhadores_15', models.TextField()),
            ],
            options={
                'get_latest_by': 'concurso',
            },
        ),
    ]
