# Generated by Django 4.0 on 2022-02-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='qtd_ganhadores_15',
            field=models.CharField(max_length=2),
        ),
    ]
