# Generated by Django 4.0 on 2022-02-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apploto', '0003_alter_sorteio_qtd_ganhadores_15'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='qtd_ganhadores_15',
            field=models.TextField(max_length=30),
        ),
        migrations.CreateModel(
            name='MeusJogos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_sorteio', models.DateField()),
                ('B1', models.SmallIntegerField()),
                ('B2', models.SmallIntegerField()),
                ('B3', models.SmallIntegerField()),
                ('B4', models.SmallIntegerField()),
                ('B5', models.SmallIntegerField()),
                ('B6', models.SmallIntegerField()),
                ('B7', models.SmallIntegerField()),
                ('B8', models.SmallIntegerField()),
                ('B9', models.SmallIntegerField()),
                ('B10', models.SmallIntegerField()),
                ('B11', models.SmallIntegerField()),
                ('B12', models.SmallIntegerField()),
                ('B13', models.SmallIntegerField()),
                ('B14', models.SmallIntegerField()),
                ('B15', models.SmallIntegerField()),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apploto.sorteio')),
            ],
            options={
                'get_latest_by': 'concurso',
            },
        ),
    ]
