# Generated by Django 4.0 on 2022-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploto', '0004_alter_sorteio_qtd_ganhadores_15_meusjogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meusjogos',
            name='concurso',
            field=models.BigIntegerField(),
        ),
    ]
