# Generated by Django 5.1.3 on 2025-06-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploto', '0005_alter_meusjogos_concurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaSenaSorteio',
            fields=[
                ('concurso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_sorteio', models.DateField()),
                ('B1', models.SmallIntegerField()),
                ('B2', models.SmallIntegerField()),
                ('B3', models.SmallIntegerField()),
                ('B4', models.SmallIntegerField()),
                ('B5', models.SmallIntegerField()),
                ('B6', models.SmallIntegerField()),
            ],
            options={
                'get_latest_by': 'concurso',
            },
        ),
        migrations.CreateModel(
            name='MeusJogosMegaSena',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('concurso', models.BigIntegerField()),
                ('data_sorteio', models.DateField()),
                ('B1', models.SmallIntegerField()),
                ('B2', models.SmallIntegerField()),
                ('B3', models.SmallIntegerField()),
                ('B4', models.SmallIntegerField()),
                ('B5', models.SmallIntegerField()),
                ('B6', models.SmallIntegerField()),
            ],
            options={
                'get_latest_by': 'concurso',
            },
        ),
    ]
